### ISSUE TITLE
实现2.0版本

### ISSUE THREAD

**Issue by otakustay** [ecomfe/emc#25]
2.0版本主要引入**异步事件**和**更新接口**两个功能，如下：
### 异步事件

当同步进行一次或多次`set(key, value)`操作时，相应触发多个事件如下：
1. 每次`set`如果值有变化，**同步**触发`changing`事件
2. 每个`set`如果值有变化，**异步**触发`change`事件
3. 所有`set`完成后，**异步**触发**一次**`update`事件

`changing`和`change`事件的`Event`对象结构如下：

``` js
{
    {string} type,
    {string} name, // 属性名
    {string} changeType, // add、change或remove
    {*} oldValue,
    {*} newValue
}
```

`update`事件的`Event`对象结构如下：

``` js
// UpdateEvent
{
    {string} type,
    {Array.<ChangeRecord>} changes
}

// ChangeRecord
{
    {string} name, // 属性名
    {*} oldValue,
    {*} newValue,
    {Object} diff // 如果是非对象的值直接更换了，或者计算不出差异的，则为null
}

// diff形式如下
{
    foo: {
        bar: {
            $update: 'change', // 有$update的才是真正变化的
            oldValue: 1,
            newValue: 2
        }
    },
    alice: {
        $update: 'add',
        oldValue: undefined,
        newValue: 3
    }
}
```
### 更新接口

参考已经实现的：https://github.com/ecomfe/ub-ria/blob/master/src/update.js

从`Model`上暴露`update`方法，以Immutable的形式更新内部数据，同样会触发各个事件

**Comment by otakustay** [comment]
`update`事件的重点在于对多次修改的合并，如：
1. 先改一个值再改回原值，`update`事件中是没有这个属性的信息的
2. 对一个对象多次进行`update`操作，需要合并成一个`diff`，这个是最难的，且不应该基于2个对象做完整的变化检测（影响效率），而是应该用多次的`command`来合并
3. 多次修改值会变成一次，如`1 -> 2 -> 3`，在`update`事件中反映出来是`1 -> 3`

**Comment by otakustay** [comment]
2.0先不实现`Collection`类，只有`Model`即可，以后再加

**Comment by otakustay** [comment]
接口上，移除`getAsModel`方法和`fill`方法，我们应该去鼓励用`update`方法

**Comment by otakustay** [comment]
罗列一下针对Object进行`update`的diff合并的可能性：
1. 一个值进行了多次`$set`操作，则取最后一次值为`newValue`
2. 先更新了`foo.bar`，又更新了`foo`，则diff中只表现`foo`。先更新`foo`再更新新的`foo.bar`也一样只表示为`foo`
3. `$extends`操作转为多个属性的`$set`的diff结果

Array在设计好diff的格式以前，不提供diff内容

**Comment by otakustay** [comment]
我将事件模型定义如下：
1. `.set`调用时同步触发`changing`事件，这个事件是可以`preventDefault()`的，也可以通过`event.value`修改最终要赋的值
2. 完成`set`操作后同步触发`change`事件
3. 全部修改完成后异步对每一个修改触发`modify`事件，内容与`change`事件相同，区别只是异步
4. 所有的修改合并后触发`update`事件，包含所有的变化

这个模型的问题在于1和2、2和3之间的关系处理

**Comment by leowang721** [comment]
9月的Issue，灰大咋样了
我还准备再拉过来用呢

**Comment by otakustay** [comment]
实现基本全了，文档中：https://github.com/ecomfe/emc/tree/2.0/feature/manual?files=1

发布的事暂缓了，我需要等 https://github.com/ecomfe/edp/issues/332 这个做完可以兼容edp和npm同时发两边
