### ISSUE TITLE
构造函数中设置的值是否应该触发相关事件

### ISSUE THREAD

**Issue by otakustay** [ecomfe/emc#27]
比如以下代码：

``` js
class MyModel extends Model {
    constructor() {
        super();

        this.on('change', () => console.log('change'));

        this.set('foo', 1);
    }
}

let model = new MyModel();
model.on('update', () => console.log('update'));
```

其中：
1. `change`是否应该打印出来
2. `update`是否应该打印出来

**Comment by errorrik** [comment]
change和update的区别是啥

**Comment by otakustay** [comment]
change是同步触发的，update是异步且会把多次change合并

**Comment by Exodia** [comment]
构造函数期间不让 set 会不会更好些， set 只在构造完毕后才能使用，能够保证实例的完整性

**Comment by otakustay** [comment]
有没有可能一个自带结构定义的Model是需要在构造函数里设置默认值的？

**Comment by Exodia** [comment]
> 有没有可能一个自带结构定义的Model是需要在构造函数里设置默认值的？

暂时没想到场景，但即便有的话，除了 model 本身，外部是肯定没法监听这个事件的，因为还在构造中；如果 model 本身有这个需求，显然在 set 的时候应该知道这东西会变化了，直接调用对应的 handler 搞就好了。

所以综上描述，我觉得要么不允许在构造器里 set，要么就不触发事件比较合适

**Comment by otakustay** [comment]
另外一个问题是是否要在emc的实现上强加这个限制，毕竟调用方可一些silent的

**Comment by Exodia** [comment]
感觉不限制适应性好些，因为实在没有什么很好的理由要限制，更多是使用者自己的考虑- -

**Comment by otakustay** [comment]
还是不控制构造函数中的事件触发（保持默认状态），有这需要的可以自行用`silent`控制
