### ISSUE TITLE
允许重新定义同名的计算属性

### ISSUE THREAD

**Issue by otakustay** [ecomfe/emc#28]
1. 重新定义时原来定义的`change`处理函数要干掉
2. 如果有已经计算的值，是否要恢复到`undefined`

**Comment by Justineo** [comment]
这个 feature 的使用场景是啥呀

**Comment by Exodia** [comment]
> 这个 feature 的使用场景是啥呀

继承的时候，如果子类不允许重新定义的话，就会造成复用问题- -

**Comment by otakustay** [comment]
> 这个 feature 的使用场景是啥呀

是的，主要是继承的场景，父类定义了一个计算属性，子类想重写这个计算属性的逻辑……

当然有办法解决，比如父类的计算属性的逻辑就是调用自己的一个方法，子类去重写这个方法，但是不是有点绕，最后就是每个计算属性对应一个方法了呗

**Comment by yibuyisheng** [comment]
> 如果有已经计算的值，是否要恢复到undefined

这个这样处理感觉怎么样：

覆盖定义计算属性之后，按照新的计算属性的逻辑重新计算一遍值。

**Comment by otakustay** [comment]
> 覆盖定义计算属性之后，按照新的计算属性的逻辑重新计算一遍值。

这样必然会再出现一次`change`事件，但这一次的事件是否是使用者想要的，我搞不明白

所以我最初的设想是通过`silent`等手段搞出一个没有事件的值变化，让这个属性的值回到最初状态

**Comment by yibuyisheng** [comment]
如果 computed 的值和其依赖的变量不同步，感觉会比较尴尬。

defineComputedProperty 是否可以给出这样的配置项：
- 定义好计算属性之后，是否要初始化地计算一把值，而不是把第一次留给依赖变量的 change ；
- 如果初始化计算了值，是不是要抛出 computed property change 的事件。

**Comment by otakustay** [comment]
我最初设回undefined的意思其实是让计算属性回到初始状态，也就是说下一次get时会计算值出来，所以其实并不会不同步

定义好后立刻计算现在就有这个配置

yibuyisheng notifications@github.com于2016年6月22日 周三下午4:32写道：

**Comment by yibuyisheng** [comment]
噢，我理解歪了一点。。。

那是不是要重新回到最初的设想了呢？

> 所以我最初的设想是通过 silent 等手段搞出一个没有事件的值变化，让这个属性的值回到最初状态。

**Comment by otakustay** [comment]
嗯，其实我最初的设想是这样的：
1. 每个计算属性有一个叫`evaluated`的状态
2. 如果发生`get`操作时，`evaluated`是`false`，则需要进行一次值计算，该次计算**不会**触发`change`
3. 依赖的属性的`change`都会触发计算属性的重新求值，该过程中会触发`change`的

而重新定义计算属性，其实是把`evaluated`状态改回`false`
